services:
  server:
    build:
      context: .
      target: final
    ports:
      - "3000:8080"
    volumes:
      - wanvi-be_wwwroot_data:/app/wwwroot  # Sử dụng đúng volume

volumes:
  wanvi-be_wwwroot_data:  # Khai báo volume đúng với container
    external: true
