name: Deploy on self-hosted runner

on:
  push:
    branches:
      - master

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run 'docker compose'
        run: docker compose up --build -d
